export const CITIES = [
  { city: 'Boston',        state: 'MA', display_name: 'Boston, MA',        slug: 'boston' },
  { city: 'New York',      state: 'NY', display_name: 'New York, NY',       slug: 'new-york' },
  { city: 'Los Angeles',   state: 'CA', display_name: 'Los Angeles, CA',    slug: 'los-angeles' },
  { city: 'Chicago',       state: 'IL', display_name: 'Chicago, IL',        slug: 'chicago' },
  { city: 'Nashville',     state: 'TN', display_name: 'Nashville, TN',      slug: 'nashville' },
  { city: 'Austin',        state: 'TX', display_name: 'Austin, TX',         slug: 'austin' },
  { city: 'Philadelphia',  state: 'PA', display_name: 'Philadelphia, PA',   slug: 'philadelphia' },
  { city: 'Atlanta',       state: 'GA', display_name: 'Atlanta, GA',        slug: 'atlanta' },
  { city: 'Seattle',       state: 'WA', display_name: 'Seattle, WA',        slug: 'seattle' },
  { city: 'Denver',        state: 'CO', display_name: 'Denver, CO',         slug: 'denver' },
  { city: 'Miami',         state: 'FL', display_name: 'Miami, FL',          slug: 'miami' },
  { city: 'Washington',    state: 'DC', display_name: 'Washington, DC',     slug: 'washington' },
  { city: 'San Francisco', state: 'CA', display_name: 'San Francisco, CA',  slug: 'san-francisco' },
  { city: 'Portland',      state: 'OR', display_name: 'Portland, OR',       slug: 'portland' },
  { city: 'Minneapolis',   state: 'MN', display_name: 'Minneapolis, MN',    slug: 'minneapolis' },
  { city: 'Dallas',        state: 'TX', display_name: 'Dallas, TX',         slug: 'dallas' },
  { city: 'Houston',       state: 'TX', display_name: 'Houston, TX',        slug: 'houston' },
  { city: 'Phoenix',       state: 'AZ', display_name: 'Phoenix, AZ',        slug: 'phoenix' },
  { city: 'Detroit',       state: 'MI', display_name: 'Detroit, MI',        slug: 'detroit' },
  { city: 'New Orleans',   state: 'LA', display_name: 'New Orleans, LA',    slug: 'new-orleans' },
] as const
